import {StyleSheet} from 'react-native';
import {
  horizontalScale,
  scaleFontSize,
  verticalScale,
} from '../../assets/styles/scaling';
const styles = StyleSheet.create({
  textBodyView: {marginTop: verticalScale(15), width: '100%'},
  textBody: {
    color: '#000000',
    fontSize: scaleFontSize(16),
    fontFamily: 'Inter-Medium',
    textAlign: 'center',
    backgroundColor: '#E7E7E7',
    paddingVertical: verticalScale(10),
  },
  textFooter: {
    color: '#FFA633',
    fontWeight: '300',
    fontSize: scaleFontSize(20),
    fontFamily: 'Inter-Light',
    textAlign: 'right',
  },
  modalStyle: {margin: 0},
  linearStyle: {
    borderRadius: horizontalScale(15),
    backgroundColor: 'white',
    elevation: 10,
    width: '90%',
    alignItems: 'center',
  },
  modalContainer: {
    alignItems: 'center',
    flex: 1,
    backgroundColor: 'rgba(193, 193, 193, 0.6)',
    justifyContent: 'center',
  },
  modalViewStyle: {
    justifyContent: 'flex-end',
    alignItems: 'flex-end',
    width: '100%',
    position: 'absolute',
    zIndex: 1,
    top: verticalScale(-20),
    right: horizontalScale(-10),
  },
  mainBorderStyle: {
    width: '90%',
    alignItems: 'center',
    paddingVertical: verticalScale(20),
  },
  itemStyle: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: horizontalScale(15),
    paddingVertical: verticalScale(6),
    width: '100%',
    alignItems: 'center',
  },
  labelTxt: {
    color: '#676767',
    fontFamily: 'Inter-Light',
    fontWeight: '200',
    fontSize: scaleFontSize(13),
    lineHeight: verticalScale(15.73),
    flex: 1,
  },
  valueTxt: {
    color: '#128807',
    fontFamily: 'Inter-Light',
    fontSize: scaleFontSize(10),
    lineHeight: verticalScale(12.1),
    textAlign: 'left',
    flex: 1,
  },
  valueTxtDisable: {
    color: '#D92507',
    fontFamily: 'Inter-Light',
    fontSize: scaleFontSize(10),
    lineHeight: verticalScale(12.1),
    textAlign: 'left',
    flex: 1,
  },
  divider: {height: 1, backgroundColor: '#CECECE', width: '100%'},
  headStyle: {
    color: '#000000',
    fontFamily: 'Inter-Regular',
    fontWeight: '500',
    fontSize: scaleFontSize(18),
    lineHeight: verticalScale(21.78),
    marginVertical: verticalScale(10),
  },
  startAddress: {
    color: '#003177',
    fontFamily: 'Inter-Regular',
    fontWeight: '400',
    fontSize: scaleFontSize(8),
    lineHeight: verticalScale(9.68),
  },
  endAddress: {
    color: '#FEB200',
    fontFamily: 'Inter-Regular',
    fontWeight: '400',
    fontSize: scaleFontSize(8),
    lineHeight: verticalScale(9.68),
  },
  icontime: {alignItems: 'center'},
  timeTxt: {
    color: '#00000050',
    fontFamily: 'Inter-Regular',
    fontSize: scaleFontSize(8),
    lineHeight: verticalScale(9.68),
  },
  tripDetails: {
    width: '90%',
  },
  fareBreak: {
    width: '90%',
    alignSelf: 'center',
    marginVertical: verticalScale(5),
    marginBottom: verticalScale(15),
  },
  fareTxt: {
    color: '#000000',
    fontFamily: 'Inter-Light',
    fontWeight: '200',
    fontSize: scaleFontSize(10),
    lineHeight: verticalScale(12.1),
  },
  fareStyle: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: horizontalScale(15),
    paddingVertical: verticalScale(2),
    width: '100%',
  },
  labelDuty: {
    color: '#000000',
    fontFamily: 'Inter-Light',
    fontWeight: '300',
    fontSize: scaleFontSize(10),
    lineHeight: verticalScale(12.1),
  },
  txtFareBreak: {
    color: '#000000',
    fontFamily: 'Inter-Regular',
    fontWeight: '300',
    fontSize: scaleFontSize(13),
    lineHeight: verticalScale(15.73),
  },
  fareTxtDark: {
    color: '#000000',
    fontFamily: 'Inter-Regular',
    fontWeight: '600',
    fontSize: scaleFontSize(10),
    lineHeight: verticalScale(12.1),
  },
  txtMode: {
    color: '#000000',
    fontFamily: 'Inter-Regular',
    fontWeight: '300',
    fontSize: scaleFontSize(13),
    lineHeight: verticalScale(15.73),
  },
  txtPayment: {
    color: '#000000',
    fontFamily: 'Inter-Light',
    fontWeight: '200',
    fontSize: scaleFontSize(10),
    lineHeight: verticalScale(12.1),
  },
  btnGotit: {
    width: '100%',
    alignItems: 'flex-end',
    justifyContent: 'center',
    marginVertical: verticalScale(5),
  },
  txtGotit: {
    color: '#003177',
    fontFamily: 'Inter-Light',
    fontWeight: '300',
    fontSize: scaleFontSize(15),
    lineHeight: verticalScale(18.15),
  },
  flexrow: {
    flexDirection: 'row',
    borderWidth: 1,
    backgroundColor: '#003177',
    borderRadius: horizontalScale(5),
  },
  input: {
    backgroundColor: '#FFFFFF',
    paddingHorizontal: horizontalScale(10),
    paddingVertical: horizontalScale(1),
    borderTopLeftRadius: horizontalScale(5),
    borderBottomLeftRadius: horizontalScale(5),

    color: '#000000',
    fontFamily: 'Inter-Regular',
    fontWeight: '400',
    fontSize: scaleFontSize(12),
  },
  percent: {
    paddingHorizontal: horizontalScale(10),
    color: '#FFFFFF',
    paddingVertical: horizontalScale(1),
    fontFamily: 'Inter-Regular',
    fontWeight: '400',
    fontSize: scaleFontSize(13),
    lineHeight: verticalScale(15.73),
  },
  percentView: {
    justifyContent: 'center',
  },
  row: {
    flexDirection: 'row',
    marginBottom: verticalScale(15),
  },
  btnCancel: {
    flex: 0.6,
    alignItems: 'flex-end',
  },
  btnSubmit: {
    flex: 0.4,
    alignItems: 'center',
  },
  txtCancel: {
    color: '#D92507B2',
    fontFamily: 'Inter-Regular',
    fontWeight: '400',
    fontSize: scaleFontSize(14),
    lineHeight: verticalScale(16.94),
  },
  txtSubmit: {
    color: '#003177',
    fontFamily: 'Inter-Regular',
    fontWeight: '400',
    fontSize: scaleFontSize(14),
    lineHeight: verticalScale(16.94),
  },
  errorView: {
    width: '90%',
    marginTop: verticalScale(10),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
  },
  errorStyle: {
    color: '#FF4444',
    fontSize: scaleFontSize(12),
    fontFamily: 'Inter-Regular',
  },
});
export default styles;
