import {StyleSheet} from 'react-native';
import {
  horizontalScale,
  scaleFontSize,
  verticalScale,
} from '../../assets/styles/scaling';
const styles = StyleSheet.create({
  textBodyView: {marginTop: verticalScale(15), width: '100%'},
  textBody: {
    color: '#000000',
    fontSize: scaleFontSize(16),
    fontFamily: 'Inter-Medium',
    textAlign: 'center',
    backgroundColor: '#E7E7E7',
    paddingVertical: verticalScale(10),
  },
  textFooter: {
    color: '#FFA633',
    fontWeight: '300',
    fontSize: scaleFontSize(20),
    fontFamily: 'Inter-Light',
    textAlign: 'right',
  },
  modalStyle: {margin: 0},
  linearStyle: {
    borderRadius: horizontalScale(30),
    backgroundColor: 'white',
    elevation: 10,
    width: '90%',
    alignItems: 'center',
  },
  modalContainer: {
    alignItems: 'center',
    flex: 1,
    backgroundColor: 'rgba(193, 193, 193, 0.6)',
    justifyContent: 'center',
  },
  modalViewStyle: {
    justifyContent: 'flex-end',
    alignItems: 'flex-end',
    width: '100%',
    position: 'absolute',
    zIndex: 1,
    top: verticalScale(-20),
    right: horizontalScale(-10),
  },
  mainBorderStyle: {
    borderColor: '#36363680',
    borderWidth: 1,
    borderRadius: horizontalScale(10),
    width: '90%',
    alignItems: 'center',
    marginVertical: verticalScale(15),
  },
  itemStyle: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: horizontalScale(15),
    paddingVertical: verticalScale(4),
    width: '100%',
  },
  addressView: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: horizontalScale(15),
    paddingVertical: verticalScale(4),
    width: '100%',
  },
  labelTxt: {
    color: '#000000',
    fontFamily: 'Inter-Medium',
    fontWeight: '400',
    fontSize: scaleFontSize(10),
    lineHeight: verticalScale(12.1),
  },
  valueTxt: {
    color: '#000000',
    fontFamily: 'Inter-Light',
    fontSize: scaleFontSize(10),
    lineHeight: verticalScale(12.1),
  },
  divider: {height: 1, backgroundColor: '#CECECE', width: '100%'},
  headStyle: {
    color: '#000000',
    fontFamily: 'Inter-Regular',
    fontWeight: '500',
    fontSize: scaleFontSize(12),
    lineHeight: verticalScale(14.52),
    marginVertical: verticalScale(10),
  },
  startAddress: {
    color: '#003177',
    fontFamily: 'Inter-Regular',
    fontWeight: '400',
    fontSize: scaleFontSize(8),
    lineHeight: verticalScale(9.68),
    width: '30%',
  },
  endAddress: {
    color: '#FEB200',
    fontFamily: 'Inter-Regular',
    fontWeight: '400',
    fontSize: scaleFontSize(8),
    lineHeight: verticalScale(9.68),
    width: '30%',
  },
  icontime: {alignItems: 'center', width: '30%'},
  timeTxt: {
    color: '#00000050',
    fontFamily: 'Inter-Regular',
    fontSize: scaleFontSize(8),
    lineHeight: verticalScale(9.68),
  },
  tripDetails: {
    width: '90%',
  },
  fareBreak: {
    width: '90%',
    alignSelf: 'center',
    marginVertical: verticalScale(5),
    marginBottom: verticalScale(15),
  },
  fareTxt: {
    color: '#000000',
    fontFamily: 'Inter-Light',
    fontWeight: '200',
    fontSize: scaleFontSize(10),
    lineHeight: verticalScale(12.1),
  },
  fareStyle: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: horizontalScale(15),
    paddingVertical: verticalScale(2),
    width: '100%',
  },
  labelDuty: {
    color: '#000000',
    fontFamily: 'Inter-Light',
    fontWeight: '300',
    fontSize: scaleFontSize(10),
    lineHeight: verticalScale(12.1),
  },
  txtFareBreak: {
    color: '#000000',
    fontFamily: 'Inter-Regular',
    fontWeight: '300',
    fontSize: scaleFontSize(13),
    lineHeight: verticalScale(15.73),
  },
  fareTxtDark: {
    color: '#000000',
    fontFamily: 'Inter-Regular',
    fontWeight: '600',
    fontSize: scaleFontSize(10),
    lineHeight: verticalScale(12.1),
  },
  txtMode: {
    color: '#000000',
    fontFamily: 'Inter-Regular',
    fontWeight: '300',
    fontSize: scaleFontSize(13),
    lineHeight: verticalScale(15.73),
  },
  txtPayment: {
    color: '#000000',
    fontFamily: 'Inter-Light',
    fontWeight: '200',
    fontSize: scaleFontSize(10),
    lineHeight: verticalScale(12.1),
  },
  btnGotit: {
    width: '100%',
    alignItems: 'flex-end',
    justifyContent: 'center',
    marginVertical: verticalScale(5),
  },
  txtGotit: {
    color: '#003177',
    fontFamily: 'Inter-Light',
    fontWeight: '300',
    fontSize: scaleFontSize(15),
    lineHeight: verticalScale(18.15),
  },
});
export default styles;
