import {StyleSheet} from 'react-native';
import {
  horizontalScale,
  scaleFontSize,
  verticalScale,
} from '../../assets/styles/scaling';

const styles = StyleSheet.create({
  logoView: {
    backgroundColor: '#013277',
    width: '100%',

    alignItems: 'center',
    shadowOffset: '#00000080',
  },
  topView: {
    backgroundColor: '#FFFFFF',
  },
  logoInnerView: {
    flexDirection: 'row',
    width: '90%',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: verticalScale(8),
  },
  userimg: {width: 40, height: 40, flex: 1, justifyContent: 'center'},

  toolbarTxt: {
    color: '#FFFFFF',
    flex: 2,
    textAlign: 'left',
    fontWeight: '600',
    fontFamily: 'Inter-Bold',
    fontSize: scaleFontSize(18),
    lineHeight: verticalScale(21.78),
  },
  listContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    height: '100%',
  },
  /* ------------card styles--------------------- */

  textBodyView: {marginTop: verticalScale(15), width: '100%'},
  textBody: {
    color: '#000000',
    fontSize: scaleFontSize(16),
    fontFamily: 'Inter-Medium',
    textAlign: 'center',
    backgroundColor: '#E7E7E7',
    paddingVertical: verticalScale(10),
  },
  textFooter: {
    color: '#FFA633',
    fontWeight: '300',
    fontSize: scaleFontSize(20),
    fontFamily: 'Inter-Light',
    textAlign: 'right',
  },
  modalStyle: {margin: 0},

  errorView: {
    width: '90%',
    marginTop: verticalScale(10),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
  },
  errorStyle: {
    color: '#FF4444',
    fontSize: scaleFontSize(12),
    fontFamily: 'Inter-Regular',
  },
  flex: {flex: 1, backgroundColor: '#FFFFFF'},
  /* -------------- */
  linearStyle: {
    borderRadius: horizontalScale(15),
    backgroundColor: 'white',
    elevation: 10,
    width: '90%',
    alignItems: 'center',
    marginBottom: verticalScale(50),
  },
  modalContainer: {
    alignItems: 'center',
    flex: 1,
    backgroundColor: 'rgba(193, 193, 193, 0.6)',
    justifyContent: 'center',
  },
  modalViewStyle: {
    justifyContent: 'flex-end',
    alignItems: 'flex-end',
    width: '100%',
  },
  mainBorderStyle: {
    width: '90%',
    alignItems: 'center',
    marginVertical: verticalScale(10),
  },
  itemStyle: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: horizontalScale(2),
    paddingVertical: verticalScale(6),
    width: '100%',
    alignItems: 'center',
  },
  itemSelfStyle: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: horizontalScale(10),
    marginVertical: verticalScale(10),
    width: '100%',
    alignItems: 'center',
  },
  labelTxt: {
    color: '#676767',
    fontFamily: 'Inter-Light',
    fontWeight: '200',
    fontSize: scaleFontSize(13),
    lineHeight: verticalScale(15.73),
    flex: 1,
  },
  valueTxt: {
    color: '#128807',
    fontFamily: 'Inter-Light',
    fontSize: scaleFontSize(10),
    lineHeight: verticalScale(12.1),
    textAlign: 'left',
    flex: 1,
  },
  valueTxtDisable: {
    color: '#D92507',
    fontFamily: 'Inter-Light',
    fontSize: scaleFontSize(10),
    lineHeight: verticalScale(12.1),
    textAlign: 'left',
    flex: 1,
  },
  divider: {height: 1, backgroundColor: '#CECECE', width: '100%'},
  headStyle: {
    color: '#000000',
    fontFamily: 'Inter-Regular',
    fontWeight: '500',
    fontSize: scaleFontSize(18),
    lineHeight: verticalScale(21.78),
    marginVertical: verticalScale(10),
    textAlign: 'left',
    width: '95%',
  },
  startAddress: {
    color: '#003177',
    fontFamily: 'Inter-Regular',
    fontWeight: '400',
    fontSize: scaleFontSize(8),
    lineHeight: verticalScale(9.68),
  },
  endAddress: {
    color: '#FEB200',
    fontFamily: 'Inter-Regular',
    fontWeight: '400',
    fontSize: scaleFontSize(8),
    lineHeight: verticalScale(9.68),
  },
  icontime: {alignItems: 'center'},
  timeTxt: {
    color: '#00000050',
    fontFamily: 'Inter-Regular',
    fontSize: scaleFontSize(8),
    lineHeight: verticalScale(9.68),
  },
  tripDetails: {
    width: '90%',
  },
  fareBreak: {
    width: '90%',
    alignSelf: 'center',
    marginVertical: verticalScale(5),
    marginBottom: verticalScale(15),
  },
  fareTxt: {
    color: '#000000',
    fontFamily: 'Inter-Light',
    fontWeight: '200',
    fontSize: scaleFontSize(10),
    lineHeight: verticalScale(12.1),
  },
  fareStyle: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: horizontalScale(15),
    paddingVertical: verticalScale(2),
    width: '100%',
  },
  labelDuty: {
    color: '#000000',
    fontFamily: 'Inter-Light',
    fontWeight: '300',
    fontSize: scaleFontSize(10),
    lineHeight: verticalScale(12.1),
  },
  txtFareBreak: {
    color: '#000000',
    fontFamily: 'Inter-Regular',
    fontWeight: '300',
    fontSize: scaleFontSize(13),
    lineHeight: verticalScale(15.73),
  },
  fareTxtDark: {
    color: '#000000',
    fontFamily: 'Inter-Regular',
    fontWeight: '600',
    fontSize: scaleFontSize(10),
    lineHeight: verticalScale(12.1),
  },
  txtMode: {
    color: '#000000',
    fontFamily: 'Inter-Regular',
    fontWeight: '300',
    fontSize: scaleFontSize(13),
    lineHeight: verticalScale(15.73),
  },
  txtPayment: {
    color: '#000000',
    fontFamily: 'Inter-Light',
    fontWeight: '200',
    fontSize: scaleFontSize(10),
    lineHeight: verticalScale(12.1),
  },
  btnGotit: {
    width: '100%',
    alignItems: 'flex-end',
    justifyContent: 'center',
    marginVertical: verticalScale(5),
  },
  txtGotit: {
    color: '#003177',
    fontFamily: 'Inter-Light',
    fontWeight: '300',
    fontSize: scaleFontSize(15),
    lineHeight: verticalScale(18.15),
  },
  flexrow: {
    flexDirection: 'row',
    borderWidth: 1,
    backgroundColor: '#003177',
    borderRadius: horizontalScale(3),
    height: '60%',
    justifyContent: 'center',
  },
  spinView: {
    flexDirection: 'row',

    width: '100%',
  },
  dateView: {
    flexDirection: 'row',
    borderRadius: horizontalScale(10),
    elevation: 5,
    backgroundColor: '#FFFFFF',
    width: '45%',
    justifyContent: 'space-between',
    paddingVertical: verticalScale(5),
    paddingHorizontal: horizontalScale(10),
    alignItems: 'center',
  },
  input: {
    backgroundColor: '#FFFFFF',
    paddingHorizontal: horizontalScale(6),
    borderTopLeftRadius: horizontalScale(3),
    borderBottomLeftRadius: horizontalScale(3),
    color: '#000000',
    fontFamily: 'Inter-Regular',
    fontWeight: '400',
    fontSize: scaleFontSize(12),
    paddingVertical: horizontalScale(1),
    justifyContent: 'flex-end',
  },
  percent: {
    paddingHorizontal: horizontalScale(6),
    color: '#FFFFFF',
    paddingVertical: horizontalScale(1),
    fontFamily: 'Inter-Regular',
    fontWeight: '400',
    fontSize: scaleFontSize(13),
    lineHeight: verticalScale(15.73),
  },
  percentView: {
    justifyContent: 'center',
  },
  row: {
    flexDirection: 'row',
    marginVertical: verticalScale(20),
  },
  btnCancel: {
    flex: 0.6,
    alignItems: 'flex-end',
  },
  btnSubmit: {
    flex: 0.4,
    alignItems: 'center',
  },
  txtCancel: {
    color: '#D92507B2',
    fontFamily: 'Inter-Regular',
    fontWeight: '400',
    fontSize: scaleFontSize(14),
    lineHeight: verticalScale(16.94),
  },
  txtSubmit: {
    color: '#003177',
    fontFamily: 'Inter-Regular',
    fontWeight: '400',
    fontSize: scaleFontSize(14),
    lineHeight: verticalScale(16.94),
  },
  radio: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  outerCircle: {
    height: horizontalScale(10),
    width: horizontalScale(10),
    borderRadius: horizontalScale(10),
    borderWidth: 1,
    borderColor: '#023C6E',
    alignItems: 'center',
    justifyContent: 'center',
  },
  innerCircle: {
    height: horizontalScale(6),
    width: horizontalScale(6),
    borderRadius: horizontalScale(6),
    backgroundColor: '#023C6E',
  },
  radioTxt: {
    paddingHorizontal: horizontalScale(5),
    fontSize: scaleFontSize(14),
    fontFamily: 'Inter-Regular',
    color: '#000000',
  },
  radioView: {
    flexDirection: 'row',
    width: '70%',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: verticalScale(8),
  },
  txtFrm: {},
  pickerview: {
    width: '100%',
    paddingHorizontal: horizontalScale(5),
    /* elevation: 10,
    borderRadius: 10, */
    justifyContent: 'center',
  },
  pickerviewIn: {
    borderWidth: 1,
    borderColor: '#D9D9D9',
    borderRadius: 5,
    paddingVertical: 2,
    paddingHorizontal: horizontalScale(5),
    width: '100%',
  },
  /* pickerStyle: {
    justifyContent: 'center',
    backgroundColor: 'green',
    paddingVertical: 50,
    borderRadius: 10,
    elevation: 10,
    paddingHorizontal: 10,
    flex: 1,
  }, */
});

export default styles;
