import {StyleSheet} from 'react-native';
import {
  horizontalScale,
  scaleFontSize,
  verticalScale,
} from '../../assets/styles/scaling';

const styles = StyleSheet.create({
  logoView: {
    backgroundColor: '#013277',
    width: '100%',

    alignItems: 'center',
    shadowOffset: '#00000080',
  },
  topView: {
    backgroundColor: '#FFFFFF',
  },
  logoInnerView: {
    flexDirection: 'row',
    width: '90%',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: verticalScale(8),
  },
  userimg: {width: 40, height: 40, flex: 1, justifyContent: 'center'},

  toolbarTxt: {
    color: '#FFFFFF',
    flex: 2,
    textAlign: 'left',
    fontWeight: '600',
    fontFamily: 'Inter-Bold',
    fontSize: scaleFontSize(18),
    lineHeight: verticalScale(21.78),
  },
  listContainer: {
    marginVertical: verticalScale(10),
    alignItems: 'center',
  },
  /* ------------card styles--------------------- */

  textBodyView: {marginTop: verticalScale(15), width: '100%'},
  textBody: {
    color: '#000000',
    fontSize: scaleFontSize(16),
    fontFamily: 'Inter-Medium',
    textAlign: 'center',
    backgroundColor: '#E7E7E7',
    paddingVertical: verticalScale(10),
  },
  textFooter: {
    color: '#FFA633',
    fontWeight: '300',
    fontSize: scaleFontSize(20),
    fontFamily: 'Inter-Light',
    textAlign: 'right',
  },
  modalStyle: {margin: 0},
  linearStyle: {
    borderRadius: horizontalScale(15),
    backgroundColor: 'white',
    elevation: 10,
    width: '95%',
    alignItems: 'center',
  },

  mainBorderStyle: {
    width: '100%',
    alignItems: 'center',
    paddingVertical: verticalScale(20),
  },
  itemStyle: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: verticalScale(6),
    width: '100%',
    alignItems: 'center',
  },
  labelTxt: {
    color: '#222222',
    fontFamily: 'Inter-regular',
    fontWeight: '400',
    fontSize: scaleFontSize(13),
    lineHeight: verticalScale(15.73),
    flex: 0.2,
  },
  valueTxt: {
    color: '#128807',
    fontFamily: 'Inter-Light',
    fontSize: scaleFontSize(10),
    lineHeight: verticalScale(12.1),
    textAlign: 'left',
    flex: 1,
  },
  valueTxtDisable: {
    color: '#D92507',
    fontFamily: 'Inter-Light',
    fontSize: scaleFontSize(10),
    lineHeight: verticalScale(12.1),
    textAlign: 'left',
    flex: 1,
  },
  divider: {height: 1, backgroundColor: '#CECECE', width: '100%'},
  headStyle: {
    color: '#000000',
    fontFamily: 'Inter-Bold',
    fontWeight: '700',
    fontSize: scaleFontSize(14),
    lineHeight: verticalScale(16.94),
    marginVertical: verticalScale(10),
    width: '80%',
    backgroundColor: '#FFFFFF',
  },
  startAddress: {
    color: '#003177',
    fontFamily: 'Inter-Regular',
    fontWeight: '400',
    fontSize: scaleFontSize(8),
    lineHeight: verticalScale(9.68),
  },
  endAddress: {
    color: '#FEB200',
    fontFamily: 'Inter-Regular',
    fontWeight: '400',
    fontSize: scaleFontSize(8),
    lineHeight: verticalScale(9.68),
  },
  icontime: {alignItems: 'center'},
  timeTxt: {
    color: '#00000050',
    fontFamily: 'Inter-Regular',
    fontSize: scaleFontSize(8),
    lineHeight: verticalScale(9.68),
  },
  tripDetails: {
    width: '90%',
  },
  fareBreak: {
    width: '90%',
    alignSelf: 'center',
    marginVertical: verticalScale(5),
    marginBottom: verticalScale(15),
  },
  fareTxt: {
    color: '#000000',
    fontFamily: 'Inter-Light',
    fontWeight: '200',
    fontSize: scaleFontSize(10),
    lineHeight: verticalScale(12.1),
  },
  fareStyle: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: horizontalScale(15),
    paddingVertical: verticalScale(2),
    width: '100%',
  },
  labelDuty: {
    color: '#000000',
    fontFamily: 'Inter-Light',
    fontWeight: '300',
    fontSize: scaleFontSize(10),
    lineHeight: verticalScale(12.1),
  },
  txtFareBreak: {
    color: '#000000',
    fontFamily: 'Inter-Regular',
    fontWeight: '300',
    fontSize: scaleFontSize(13),
    lineHeight: verticalScale(15.73),
  },
  fareTxtDark: {
    color: '#000000',
    fontFamily: 'Inter-Regular',
    fontWeight: '600',
    fontSize: scaleFontSize(10),
    lineHeight: verticalScale(12.1),
  },
  txtMode: {
    color: '#000000',
    fontFamily: 'Inter-Regular',
    fontWeight: '300',
    fontSize: scaleFontSize(13),
    lineHeight: verticalScale(15.73),
  },
  txtPayment: {
    color: '#000000',
    fontFamily: 'Inter-Light',
    fontWeight: '200',
    fontSize: scaleFontSize(10),
    lineHeight: verticalScale(12.1),
  },
  btnGotit: {
    width: '100%',
    alignItems: 'flex-end',
    justifyContent: 'center',
    marginVertical: verticalScale(5),
  },
  txtGotit: {
    color: '#003177',
    fontFamily: 'Inter-Light',
    fontWeight: '300',
    fontSize: scaleFontSize(15),
    lineHeight: verticalScale(18.15),
  },
  flexrow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  input: {
    backgroundColor: '#FFFFFF',
    paddingHorizontal: horizontalScale(10),
    paddingVertical: horizontalScale(1),

    color: '#000000',
    fontFamily: 'Inter-Regular',
    fontWeight: '400',
    fontSize: scaleFontSize(10),
    marginBottom: 10,
    borderBottomColor: '#ccc',
  },
  percent: {
    paddingHorizontal: horizontalScale(10),
    color: '#FFFFFF',
    paddingVertical: horizontalScale(1),
    fontFamily: 'Inter-Regular',
    fontWeight: '400',
    fontSize: scaleFontSize(13),
    lineHeight: verticalScale(15.73),
  },
  percentView: {
    justifyContent: 'center',
  },
  row: {
    flexDirection: 'row',
    marginTop: verticalScale(15),
  },
  btnCancel: {
    flex: 0.6,
    alignItems: 'flex-end',
  },
  btnSubmit: {
    flex: 0.4,
    alignItems: 'center',
  },
  txtCancel: {
    color: '#003177',
    fontFamily: 'Inter-Regular',
    fontWeight: '400',
    fontSize: scaleFontSize(14),
    lineHeight: verticalScale(16.94),
    borderRadius: horizontalScale(3),
    paddingHorizontal: horizontalScale(10),
    paddingVertical: verticalScale(5),
    borderWidth: 1,
    borderColor: '#003177',
  },
  txtSubmit: {
    color: '#FFFFFF',
    fontFamily: 'Inter-Regular',
    fontWeight: '400',
    fontSize: scaleFontSize(14),
    lineHeight: verticalScale(16.94),
    borderRadius: horizontalScale(3),
    paddingHorizontal: horizontalScale(10),
    paddingVertical: verticalScale(5),
    borderWidth: 1,
    backgroundColor: '#003177',
    borderColor: '#003177',
  },
  errorView: {
    width: '90%',
    marginTop: verticalScale(10),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
  },
  errorStyle: {
    color: '#FF4444',
    fontSize: scaleFontSize(12),
    fontFamily: 'Inter-Regular',
  },
  flex: {flex: 1, backgroundColor: '#FFFFFF'},
});

export default styles;
