import {StyleSheet} from 'react-native';
import {
  horizontalScale,
  scaleFontSize,
  verticalScale,
} from '../../assets/styles/scaling';

const styles = StyleSheet.create({
  flex: {flex: 1, alignItems: 'center', backgroundColor: '#FFFFFF'},
  searchView: {
    borderRadius: horizontalScale(10),
    elevation: 10,

    flexDirection: 'row',
    alignItems: 'center',
    width: '95%',
    shadowColor: '#000000',
    backgroundColor: '#003177',
    marginVertical: verticalScale(10),
    shadowOpacity: 0.8,
    shadowRadius: 2,
    shadowOffset: {
      height: 1,
      width: 1,
    },
  },
  searchBtn: {flex: 0.1, alignItems: 'center'},
  sarchInput: {
    flex: 0.9,
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: horizontalScale(10),
    borderBottomLeftRadius: horizontalScale(10),
    paddingVertical: verticalScale(5),
    paddingHorizontal: verticalScale(15),
  },
  itemView: {
    borderRadius: horizontalScale(5),
    elevation: 10,
    flexDirection: 'row',
    alignItems: 'center',
    width: '95%',
    backgroundColor: '#FFFFFF',
    marginVertical: verticalScale(5),
    justifyContent: 'space-between',
    paddingVertical: verticalScale(10),
    paddingHorizontal: verticalScale(15),
    shadowColor: '#00000033',
    shadowOpacity: 0.8,
    shadowRadius: 2,
    shadowOffset: {
      height: 1,
      width: 1,
    },
  },
  listContainer: {
    width: '100%',
    alignItems: 'flex-end',
    paddingBottom: verticalScale(50),
    height: '40%',
  },

  nodataview: {alignItems: 'center', justifyContent: 'center', flex: 1},
  nodatatext: {
    textAlign: 'center',
    color: '#222222',
    fontWeight: '400',
    fontFamily: 'Inter-Regular',
    fontSize: scaleFontSize(21),
    lineHeight: verticalScale(25.41),
  },
  flexrow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  driverInfo: {
    paddingHorizontal: horizontalScale(10),
  },
  txtValue: {
    paddingHorizontal: horizontalScale(10),
    paddingVertical: verticalScale(2),
    color: '#222222',
    fontWeight: '400',
    fontFamily: 'Inter-Regular',
    fontSize: scaleFontSize(8),
    lineHeight: verticalScale(9.68),
    textAlign: 'left',
  },
  reviewView: {alignItems: 'center'},
  more: {
    color: '#003177',
    fontWeight: '300',
    fontFamily: 'Inter-Regular',
    fontSize: scaleFontSize(12),
    lineHeight: verticalScale(14.52),
  },
  review: {
    color: '#0069FF',
    fontWeight: '300',
    fontFamily: 'Inter-Regular',
    fontSize: scaleFontSize(12),
    lineHeight: verticalScale(14.52),
  },
  imgCircle: {
    width: 50,
    height: 50,
    borderRadius: 25,
    borderColor: '#000000',
    borderWidth: 2,
    borderStyle: 'dashed',
    alignItems: 'center',
    justifyContent: 'center',
  },
  txtStatus: {
    paddingHorizontal: horizontalScale(2),
    paddingVertical: verticalScale(2),
    color: '#128807',
    fontWeight: '400',
    fontFamily: 'Inter-Regular',
    fontSize: scaleFontSize(10),
    lineHeight: verticalScale(12.1),
    textAlign: 'left',
  },
  driverRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: verticalScale(2),
  },
  txtLabel: {
    color: '#222222',
    fontWeight: '400',
    fontFamily: 'Inter-Regular',
    fontSize: scaleFontSize(8),
    lineHeight: verticalScale(9.68),
    textAlign: 'left',
  },
  txtRegNo: {
    paddingVertical: verticalScale(2),
    color: '#222222',
    fontWeight: '400',
    fontFamily: 'Inter-Regular',
    fontSize: scaleFontSize(12),
    lineHeight: verticalScale(14.52),
    textAlign: 'left',
    marginRight: horizontalScale(2),
  },
  colorGreen: {
    color: '#128807',
    paddingVertical: verticalScale(2),
    fontWeight: '400',
    fontFamily: 'Inter-Regular',
    fontSize: scaleFontSize(12),
    lineHeight: verticalScale(14.52),
    textAlign: 'left',
    marginRight: horizontalScale(2),
  },

  colorOrange: {
    color: '#FF7A00',
    paddingVertical: verticalScale(2),
    fontWeight: '400',
    fontFamily: 'Inter-Regular',
    fontSize: scaleFontSize(12),
    lineHeight: verticalScale(14.52),
    textAlign: 'left',
    marginRight: horizontalScale(2),
  },

  colorRed: {
    color: '#D92507',
    paddingVertical: verticalScale(2),
    fontWeight: '400',
    fontFamily: 'Inter-Regular',
    fontSize: scaleFontSize(12),
    lineHeight: verticalScale(14.52),
    textAlign: 'left',
    marginRight: horizontalScale(2),
  },
  button: {
    backgroundColor: 'gray',
    paddingVertical: 5,
    paddingHorizontal: 10,
    borderRadius: 20,
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
  },
  buttonActive: {
    backgroundColor: 'green',
    justifyContent: 'flex-end',
  },
  circle: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: 'white',
    marginRight: 5,
  },
  circleActive: {
    marginLeft: 5,
  },
  /* Switch */
  pressable: {
    width: 25,
    height: 13,
    borderRadius: 16,
  },
  backgroundGradient: {
    borderRadius: horizontalScale(16),
    flex: 1,
    borderColor: '#FEB200',
    borderWidth: 1,
  },
  innerContainer: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    flex: 1,
    position: 'relative',
  },
  headGradient: {
    width: 10,
    height: 10,
    borderRadius: 100,
  },
});

export default styles;
