import {StyleSheet} from 'react-native';
import {
  horizontalScale,
  scaleFontSize,
  verticalScale,
} from '../../assets/styles/scaling';
const styles = StyleSheet.create({
  textBodyView: {marginTop: verticalScale(15), width: '100%'},
  textBody: {
    color: '#000000',
    fontSize: scaleFontSize(16),
    fontFamily: 'Inter-Medium',
    textAlign: 'center',
    backgroundColor: '#E7E7E7',
    paddingVertical: verticalScale(10),
  },
  textFooter: {
    color: '#FFA633',
    fontWeight: '300',
    fontSize: scaleFontSize(20),
    fontFamily: 'Inter-Light',
    textAlign: 'right',
  },
  modalStyle: {margin: 0},
  linearStyle: {
    borderTopLeftRadius: horizontalScale(20),
    borderTopRightRadius: horizontalScale(20),
    backgroundColor: 'white',
    elevation: 10,
    width: '100%',
    alignItems: 'center',
    height: '70%',
  },
  modalContainer: {
    alignItems: 'center',
    flex: 1,
    backgroundColor: 'rgba(193, 193, 193, 0.6)',
    justifyContent: 'flex-end',
  },
  modalViewStyle: {
    justifyContent: 'flex-end',
    alignItems: 'flex-end',
    width: '100%',
    position: 'absolute',
    zIndex: 1,
    top: verticalScale(-50),
    right: horizontalScale(120),
  },
  mainBorderStyle: {
    width: '90%',
    alignItems: 'center',
    marginTop: verticalScale(50),
  },
  itemStyle: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: horizontalScale(15),
    paddingVertical: verticalScale(4),
    width: '100%',
  },
  labelTxt: {
    color: '#000000',
    fontFamily: 'Inter-Medium',
    fontWeight: '400',
    fontSize: scaleFontSize(10),
    lineHeight: verticalScale(12.1),
  },
  valueTxt: {
    color: '#000000',
    fontFamily: 'Inter-Light',
    fontSize: scaleFontSize(10),
    lineHeight: verticalScale(12.1),
  },
  divider: {height: 1, backgroundColor: '#CECECE', width: '100%'},
  headStyle: {
    color: '#000000',
    fontFamily: 'Inter-Regular',
    fontWeight: '500',
    fontSize: scaleFontSize(12),
    lineHeight: verticalScale(14.52),
    marginVertical: verticalScale(10),
  },
  startAddress: {
    color: '#003177',
    fontFamily: 'Inter-Regular',
    fontWeight: '400',
    fontSize: scaleFontSize(8),
    lineHeight: verticalScale(9.68),
  },
  endAddress: {
    color: '#FEB200',
    fontFamily: 'Inter-Regular',
    fontWeight: '400',
    fontSize: scaleFontSize(8),
    lineHeight: verticalScale(9.68),
  },
  icontime: {alignItems: 'center'},
  timeTxt: {
    color: '#00000050',
    fontFamily: 'Inter-Regular',
    fontSize: scaleFontSize(8),
    lineHeight: verticalScale(9.68),
  },
  tripDetails: {
    width: '95%',
    paddingTop: verticalScale(10),
    paddingBottom: verticalScale(130),
  },
  fareBreak: {
    width: '90%',
    alignSelf: 'center',
    marginVertical: verticalScale(5),
    marginBottom: verticalScale(15),
  },
  fareTxt: {
    color: '#000000',
    fontFamily: 'Inter-Light',
    fontWeight: '200',
    fontSize: scaleFontSize(10),
    lineHeight: verticalScale(12.1),
  },
  fareStyle: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: horizontalScale(15),
    paddingVertical: verticalScale(2),
    width: '100%',
  },
  labelDuty: {
    color: '#000000',
    fontFamily: 'Inter-Light',
    fontWeight: '300',
    fontSize: scaleFontSize(10),
    lineHeight: verticalScale(12.1),
  },
  txtFareBreak: {
    color: '#000000',
    fontFamily: 'Inter-Regular',
    fontWeight: '300',
    fontSize: scaleFontSize(13),
    lineHeight: verticalScale(15.73),
  },
  fareTxtDark: {
    color: '#000000',
    fontFamily: 'Inter-Regular',
    fontWeight: '600',
    fontSize: scaleFontSize(10),
    lineHeight: verticalScale(12.1),
  },
  txtMode: {
    color: '#000000',
    fontFamily: 'Inter-Regular',
    fontWeight: '300',
    fontSize: scaleFontSize(13),
    lineHeight: verticalScale(15.73),
  },
  txtPayment: {
    color: '#000000',
    fontFamily: 'Inter-Light',
    fontWeight: '200',
    fontSize: scaleFontSize(10),
    lineHeight: verticalScale(12.1),
  },
  btnGotit: {
    width: '100%',
    alignItems: 'flex-end',
    justifyContent: 'center',
    marginVertical: verticalScale(5),
  },
  txtGotit: {
    color: '#003177',
    fontFamily: 'Inter-Light',
    fontWeight: '300',
    fontSize: scaleFontSize(15),
    lineHeight: verticalScale(18.15),
  },
  imgCircle: {
    width: 110,
    height: 110,
    borderRadius: 55,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  img: {
    width: 80,
    height: 80,
  },
  itemView: {
    borderRadius: horizontalScale(5),
    elevation: 10,
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
    backgroundColor: '#FFFFFF',
    marginVertical: verticalScale(5),
    justifyContent: 'space-between',
    paddingVertical: verticalScale(5),
    paddingHorizontal: verticalScale(5),
    shadowColor: '#00000050',
    shadowOpacity: 0.8,
    shadowRadius: 2,
    shadowOffset: {
      height: 1,
      width: 1,
    },
  },
  flexrow: {
    flexDirection: 'row',
  },
  driverInfo: {
    paddingHorizontal: horizontalScale(1),
  },
  txtUser: {
    paddingHorizontal: horizontalScale(5),
    paddingVertical: verticalScale(1),
    color: '#222222',
    fontWeight: '400',
    fontFamily: 'Inter-Regular',
    fontSize: scaleFontSize(12),
    lineHeight: verticalScale(14.52),
    textAlign: 'left',
  },
  driverRow: {
    flexDirection: 'row',
  },
});
export default styles;
