import {StyleSheet} from 'react-native';
import {
  horizontalScale,
  scaleFontSize,
  verticalScale,
} from '../../assets/styles/scaling';

const styles = StyleSheet.create({
  logoView: {
    backgroundColor: '#013277',
    width: '100%',
    elevation: 10,
    borderBottomLeftRadius: horizontalScale(15),
    borderBottomRightRadius: horizontalScale(15),
    alignItems: 'center',
    height: '8%',
    shadowOffset: '#00000080',
  },
  logoInnerView: {
    flexDirection: 'row',
    width: '90%',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: verticalScale(8),
  },
  flex: {
    flex: 1,
  },
  userimg: {width: 40, height: 40},
  whiteView: {
    flex: 4,
    backgroundColor: 'white',
  },
  viewOne: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    flex: 1,
    marginVertical: verticalScale(10),
  },
  viewTwo: {
    flex: 1,
    marginVertical: verticalScale(20),
    alignItems: 'center',
  },
  viewThree: {
    /*
    borderRadius: horizontalScale(10),
    justifyContent: 'space-around',
     */

    alignItems: 'center',
  },
  viewThreeInner: {
    backgroundColor: '#074088',
    borderRadius: horizontalScale(10),
    justifyContent: 'space-around',
    alignItems: 'center',
    width: '95%',
  },
  viewFour: {
    alignItems: 'center',
  },
  viewFourInner: {
    backgroundColor: '#EFEFEF',
    borderRadius: horizontalScale(10),
    width: '95%',
    marginVertical: verticalScale(10),
  },
  txtCardTitle: {
    color: '#FFFFFF',
    backgroundColor: '#013277',
    borderTopLeftRadius: horizontalScale(15),
    borderTopRightRadius: horizontalScale(15),
    width: '100%',
    paddingVertical: verticalScale(5),
    textAlign: 'center',
  },
  txtCardAmount: {
    color: '#222222',
    fontSize: scaleFontSize(15),
    lineHeight: verticalScale(18.15),
    fontWeight: '600',
    fontFamily: 'Inter-SemiBold',
    width: '100%',
    paddingVertical: verticalScale(5),
    textAlign: 'center',
  },
  txtCardRides: {
    color: '#222222',
    fontSize: scaleFontSize(8),
    lineHeight: verticalScale(9.68),
    fontWeight: '400',
    fontFamily: 'Inter-Regular',
    paddingStart: horizontalScale(5),
  },
  cardRides: {
    flexDirection: 'row',
    width: '100%',
    paddingVertical: verticalScale(5),
    marginHorizontal: horizontalScale(10),
    alignItems: 'center',
  },
  cardCount: {
    flexDirection: 'row',
    width: '100%',
    paddingVertical: verticalScale(15),
    marginHorizontal: horizontalScale(10),
    alignItems: 'center',
  },
  payHistory: {
    flexDirection: 'row',
    width: '80%',
    paddingVertical: verticalScale(5),
    marginHorizontal: horizontalScale(10),
    justifyContent: 'space-between',
  },
  smallCard: {
    elevation: 10,
    backgroundColor: '#EFEFEF',
    borderColor: '#000000',
    width: '90%',
    borderRadius: horizontalScale(15),
    height: '48%',
  },
  topCardView: {
    width: '40%',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: horizontalScale(5),
  },
  topCardOnlineView: {
    width: '60%',
    alignItems: 'center',
    height: '100%',
    marginTop: horizontalScale(5),
  },
  onlineCard: {
    elevation: 10,
    backgroundColor: '#EFEFEF',
    borderColor: '#000000',
    width: '90%',
    borderRadius: horizontalScale(15),
    height: '100%',
  },
  divider: {height: 0.3, backgroundColor: '#22222250', width: '100%'},
  dividerDark: {height: 0.3, backgroundColor: '#22222250', width: '100%'},
  txtOnlineWait: {
    color: '#222222',
    fontSize: scaleFontSize(10),
    lineHeight: verticalScale(12.1),
    fontWeight: '400',
    fontFamily: 'Inter-Regular',
    paddingStart: horizontalScale(5),
  },
  txtOnlinetrip: {
    color: '#128807',
    fontSize: scaleFontSize(10),
    lineHeight: verticalScale(12.1),
    fontWeight: '400',
    fontFamily: 'Inter-Regular',
    paddingStart: horizontalScale(5),
    width: '100%',
  },
  txtOffline: {
    color: '#D92507',
    fontSize: scaleFontSize(10),
    lineHeight: verticalScale(12.1),
    fontWeight: '400',
    fontFamily: 'Inter-Regular',
    paddingStart: horizontalScale(5),
  },
  blueHeader: {
    backgroundColor: '#013277',
    borderTopLeftRadius: horizontalScale(15),
    borderTopRightRadius: horizontalScale(15),
    width: '100%',
  },
  txtvehiclecount: {
    backgroundColor: '#FEB200',
    paddingHorizontal: 15,
    paddingVertical: 2,
    borderRadius: 5,
    color: '#FFFFFF',
    fontSize: 12,
  },
  txtSmallWhite: {
    color: '#FFFFFF',
    fontWeight: '600',
    fontSize: scaleFontSize(10),
    lineHeight: verticalScale(12.1),
    fontFamily: 'Inter-Regular',
    marginVertical: verticalScale(10),
  },
  txtMediumWhite: {
    color: '#FFFFFF',
    fontWeight: '600',
    fontSize: scaleFontSize(15),
    lineHeight: verticalScale(18.15),
    marginVertical: verticalScale(5),
    fontFamily: 'Inter-Regular',
  },
  txtListTitle: {
    color: '#000000',
    fontFamily: 'Inter-Regular',
    fontWeight: '600',
    fontSize: scaleFontSize(13),
    lineHeight: verticalScale(16),
  },
  txtListCount: {
    color: '#FFFFFF',
    fontFamily: 'Inter-Regular',
    fontWeight: '600',
    fontSize: scaleFontSize(10),
    lineHeight: verticalScale(16),
  },
  txtListHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: horizontalScale(20),
    paddingVertical: verticalScale(10),
  },
  listStyle: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: verticalScale(5),
  },
  userName: {
    marginVertical: verticalScale(10),
    paddingHorizontal: horizontalScale(20),
  },
  incomeReport: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '90%',
  },
  graphView: {
    elevation: 10,
    borderRadius: horizontalScale(10),
    marginVertical: verticalScale(5),
  },
  countCircle: {
    backgroundColor: '#064691',
    borderRadius: horizontalScale(8),
    width: horizontalScale(16),
    height: verticalScale(16),

    alignItems: 'center',
    justifyContent: 'center',
  },
  incomeTxt: {
    color: '#003177',
    fontFamily: 'Inter-Regular',
    fontWeight: '600',
    fontSize: scaleFontSize(13),
    lineHeight: verticalScale(16),
  },
  colorGreen: {
    color: '#128807',
    paddingVertical: verticalScale(2),
    fontWeight: '400',
    fontFamily: 'Inter-Regular',
    fontSize: scaleFontSize(12),
    lineHeight: verticalScale(14.52),
    textAlign: 'left',
    marginRight: horizontalScale(2),
  },

  colorOrange: {
    color: '#FEB200',
    paddingVertical: verticalScale(2),
    fontWeight: '400',
    fontFamily: 'Inter-Regular',
    fontSize: scaleFontSize(12),
    lineHeight: verticalScale(14.52),
    textAlign: 'left',
    marginRight: horizontalScale(2),
  },
  colorRed: {
    color: '#D92507',
    paddingVertical: verticalScale(2),
    fontWeight: '400',
    fontFamily: 'Inter-Regular',
    fontSize: scaleFontSize(12),
    lineHeight: verticalScale(14.52),
    textAlign: 'left',
    marginRight: horizontalScale(2),
  },
  listItems: {
    paddingHorizontal: horizontalScale(20),
  },
});

export default styles;
