import {StyleSheet} from 'react-native';
import {
  horizontalScale,
  scaleFontSize,
  verticalScale,
} from '../../assets/styles/scaling';

const styles = StyleSheet.create({
  svgcontainer: {
    flex: 1,
    justifyContent: 'space-between',
  },
  flex: {flex: 1, backgroundColor: 'white'},
  end: {alignSelf: 'flex-end'},
  animView: {
    flex: 1.5,
    alignItems: 'flex-end',
  },
  forgotView: {
    marginHorizontal: horizontalScale(20),
    flex: 1.5,
    justifyContent: 'center',
  },
  mainView: {position: 'absolute', width: '100%', height: '100%'},
  close: {marginTop: 15, marginRight: 50},
  anim: {
    width: '100%',
    height: '100%',
    alignItems: 'center',
  },
  animImg: {width: '100%', height: '70%', flex: 0.7},
  tvSubmit: {
    color: '#FFFFFF',
    fontFamily: 'Inter-SemiBold',
    fontWeight: '700',
    fontSize: scaleFontSize(15),
    lineHeight: verticalScale(18.15),
    textAlign: 'center',
  },
  btnSubmit: {
    backgroundColor: '#FEB200',
    borderRadius: horizontalScale(10),
    paddingVertical: verticalScale(8),
    marginVertical: verticalScale(30),
  },
  tvSubtitle: {
    color: '#222222',
    fontFamily: 'Inter-Medium',
    fontWeight: '400',
    fontSize: scaleFontSize(12),
    lineHeight: verticalScale(14.52),
    textAlign: 'center',
    marginVertical: verticalScale(5),
  },
  tvBlue: {
    color: '#003286',
    fontFamily: 'Inter-Bold',
    fontWeight: '800',
    fontSize: scaleFontSize(24),
    lineHeight: verticalScale(29.05),
    textAlign: 'center',
    marginVertical: verticalScale(5),
  },
  tvYellow: {
    color: '#FEB200',
    fontFamily: 'Inter-Bold',
    fontWeight: '800',
    fontSize: scaleFontSize(24),
    lineHeight: verticalScale(29.05),
    textAlign: 'center',
  },
  tvLabel: {
    color: '#222222',
    fontFamily: 'Inter-Regular',
    fontWeight: '700',
    fontSize: scaleFontSize(15),
    lineHeight: verticalScale(18.15),
    textAlign: 'left',
    marginTop: verticalScale(15),
    marginBottom: verticalScale(5),
  },
  etMobile: {
    backgroundColor: '#D9D9D980',
    width: '80%',
    paddingVertical: verticalScale(5),
    paddingHorizontal: horizontalScale(15),
    fontFamily: 'Inter-Regular',
    fontWeight: '700',
    fontSize: scaleFontSize(12),
    lineHeight: verticalScale(14.52),
  },
  errorView: {
    width: '90%',
    marginTop: verticalScale(10),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
  },
  errorStyle: {
    color: '#FF4444',
    fontSize: scaleFontSize(12),
    fontFamily: 'Inter-Regular',
  },
  countryBtn: {
    backgroundColor: '#A3A2A2',
    borderTopLeftRadius: horizontalScale(10),
    borderBottomLeftRadius: horizontalScale(10),
    justifyContent: 'center',
    paddingHorizontal: horizontalScale(15),
    width: '20%',
  },
  country: {
    color: '#000000',
    fontWeight: '700',
    fontFamily: 'Inter-Bold',
    fontSize: scaleFontSize(12),
    lineHeight: verticalScale(14.52),
  },
  mobileStyle: {
    flexDirection: 'row',
    borderColor: '#023C6E',
    borderWidth: 1,
    borderRadius: horizontalScale(10),
    width: '100%',
    marginVertical: verticalScale(5),
  },
  keyboardAvoidStyle: {flex: 1.5},
  scrollContentStyle: {
    flexGrow: 0.5,
    justifyContent: 'center',
    alignItems: 'center',
  },
  scrollStyle: {flex: 1, width: '100%'},
  keybAvoid: {
    flex: 1,
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'flex-end',
  },
  keybAvoidFocused: {
    flex: 1,
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'flex-end',
  },
  focusedView: {
    flex: 1.5,
    alignItems: 'center',
  },
  tvWhite: {
    color: '#FFFFFF',
    fontFamily: 'Inter-Bold',
    fontWeight: '800',
    fontSize: scaleFontSize(24),
    lineHeight: verticalScale(29.05),
    textAlign: 'center',
    marginVertical: verticalScale(5),
  },
  secondViewContainer: {
    position: 'absolute',
    top: 0,
    zIndex: 1,
  },
});

export default styles;
