export const Routes = {
  Home: 'Home',
  Profile: 'Profile',
  Splash: 'Splash Screen',
  Login: 'Login',
  Onboard: 'Onboard Screen',
  Forgot: 'Forgot Password',
  Otp: 'Otp Screen',
  Change: 'ChangePassword',
  Reset: 'Password Reset',
  Dashboard: 'Main Screen',
  EditProfile: 'EditProfile',
  Reviews: 'Reviews',
  Earnings: 'Earnings',
  ManageVehicleTabs: 'ManageVehicleTabs',
  VehicleDetails: 'VehicleDetails',
  ManageDriver: 'ManageDriver',
  DriverDetails: 'DriverDetails',
  TrackVehicleTabs: 'TrackVehicleTabs',
  TrackScreen: 'TrackScreen',
  VehicleStatusTabs: 'VehicleStatusTabs',
  OfferDealTabs: 'OfferDealTabs',
  BasicPriceTabs: 'BasicPriceTabs',
  PeriodicPriceTabs: 'PeriodicPriceTabs',
  ManageBasicRates: 'ManageBasicRates',
  ManagePeriodicRates: 'ManagePeriodicRates',
  SubscribeTabs: 'SubscribeTabs',
  Language: 'Language',
  OnlineCardTabs: 'OnlineCardTabs',
};
